---
- name: Add php apt repo key
  apt_key:
    url: "https://packages.sury.org/php/apt.gpg"
    state: present

- name: Add php apt repository
  apt_repository:
    repo: "deb https://packages.sury.org/php/ stretch main"
    state: present

- name: include geerlingguy.php-versions role
  include_role:
    name: geerlingguy.php-versions

- name: include geerlingguy.php role
  include_role:
    vars_from: "main.yml"
    name: geerlingguy.php

- name: Ensure php packages are installed
  apt:
    name:
      - php
      - php-common
      - php-cli
      - php-intl
      - php-curl
      - php-cgi
      - php-fpm
      - php-mysql
      - php-mbstring
      - php-dom
      - php-zip
      - php-opcache
      - php-xml
      - php-apcu
      - php-gd
    state: present

- name: include geerlingguy.composer role
  include_role:
    name: geerlingguy.composer
