---
- name: Add php apt repo key
  apt_key:
    url: "https://packages.sury.org/php/apt.gpg"
    state: present

- name: Add php apt repository
  apt_repository:
    repo: "deb https://packages.sury.org/php/ stretch main"
    state: present

- include_role:
  name: geerlingguy.php-versions

- include_role:
  name: geerlingguy.php

- include_role:
  name: geerlingguy.composer