---
- name: Add php apt repo key
  apt_key:
    url: "https://packages.sury.org/php/apt.gpg"
    state: present

- name: Add php apt repository
  apt_repository:
    repo: "deb https://packages.sury.org/php/ stretch main"
    state: present

- name: include geerlingguy.php-versions role
  include_role:
    name: geerlingguy.php-versions

- name: include geerlingguy.php role
  include_role:
    name: geerlingguy.php

- name: Ensure php packages are installed
  apt:
    name:
      - php{{ php_version }}
      - php{{ php_version }}-common
      - php{{ php_version }}-cli
      - php{{ php_version }}-intl
      - php{{ php_version }}-curl
      - php{{ php_version }}-cgi
      - php{{ php_version }}-fpm
      - php{{ php_version }}-mysql
      - php{{ php_version }}-mbstring
      - php{{ php_version }}-dom
      - php{{ php_version }}-zip
      - php{{ php_version }}-opcache
      - php{{ php_version }}-xml
      - php{{ php_version }}-apcu
      - php{{ php_version }}-gd
      - php{{ php_version }}-redis
    state: present

- name: include geerlingguy.composer role
  include_role:
    name: geerlingguy.composer
